package com.drpicox.game.idea;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221124_SawmillStrollIdea_Test {

    @Autowired Post_20221124_SawmillStrollIdea_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-11-24_sawmill_stroll_idea", "5ede492b1e0c4828764614853b1e0b94");
        context.beforeTest();

        // # Sawmill Stroll idea                                                        // # Sawmill Stroll idea

        // ## How to get sawmill stroll idea?                                           // ## How to get sawmill stroll idea?
        context.givenANewGameWithAStackOfNSCardsAndNSCard(1, "Sawmill", 1, "Villager"); // * Given a new game with a stack of 1 "Sawmill" cards and 1 "Villager" card.
        context.endTheCurrentMoon();                                                    // * End the current moon.
        context.thereShouldBeTheSIdea("Sawmill Stroll Idea");                           // * There should be the "Sawmill Stroll Idea" idea.
        context.theSShouldHaveLevelNAndNXp("Sawmill Stroll Idea", 1, 0);                // * The "Sawmill Stroll Idea" should have level 1 and 0 XP.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
