package com.drpicox.game.idea;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221128_SnowyMountainStrollIdea_Test {

    @Autowired Post_20221128_SnowyMountainStrollIdea_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-11-28_snowy_mountain_stroll_idea", "0136f563ec80ae4baea8f8eed7213b96");
        context.beforeTest();

        // # Snowy Mountain Stroll idea                                                        // # Snowy Mountain Stroll idea

        // ## How to get Snowy Mountain stroll idea?                                           // ## How to get Snowy Mountain stroll idea?
        context.givenANewGameWithAStackOfNSCardsAndNSCard(1, "Snowy Mountain", 1, "Villager"); // * Given a new game with a stack of 1 "Snowy Mountain" cards and 1 "Villager" card.
        context.endTheCurrentMoon();                                                           // * End the current moon.
        context.thereShouldBeTheSIdea("Snowy Mountain Stroll Idea");                           // * There should be the "Snowy Mountain Stroll Idea" idea.
        context.theSShouldHaveLevelNAndNXp("Snowy Mountain Stroll Idea", 1, 0);                // * The "Snowy Mountain Stroll Idea" should have level 1 and 0 XP.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
