package com.drpicox.game.idea;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221124_ArcherWithArrowKill_Test {

    @Autowired Post_20221124_ArcherWithArrowKill_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-11-24_archer_with_arrow_kill", "6e9058b3f4fd79f0bc06693c19064fd1");
        context.beforeTest();

        // # Archer with arrow kill                                                          // # Archer with arrow kill

        // ## How archer kills?                                                              // ## How archer kills?
        context.givenANewGameWithAStackOfNSNSAndNSCards(1, "Archer", 1, "Arrow", 1, "Wolf"); // * Given a new game with a stack of 1 "Archer", 1 "Arrow" and 1 "Wolf" cards.
        context.endTheCurrentMoon();                                                         // * End the current moon.
        context.thereShouldBeAStackWithNSNSAndNSCards(1, "Archer", 0, "Arrow", 0, "Wolf");   // * There should be a stack with 1 "Archer", 0 "Arrow" and 0 "Wolf" cards.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
