package com.drpicox.game.idea;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221124_MagicIdea_Test {

    @Autowired Post_20221124_MagicIdea_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-11-24_magic_idea", "fd40e164beb8f8ba9a43675b27826aad");
        context.beforeTest();

        // # Magic idea                                         // # Magic idea

        // ## How to acquire Magic Idea?                        // ## How to acquire Magic Idea?
        context.givenANewGameWithAStackOfNSCard(1, "Wizard");   // * Given a new game with a stack of 1 "Wizard" card.
        context.endTheCurrentMoon();                            // * End the current moon.
        context.thereShouldBeTheSIdea("Magic Idea");            // * There should be the "Magic Idea" idea.
        context.theSShouldHaveLevelNAndNXp("Magic Idea", 1, 0); // * The "Magic Idea" should have level 1 and 0 XP.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
