package com.drpicox.game.idea;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20220725_IdeasHaveLevels_Test {

    @Autowired Post_20220725_IdeasHaveLevels_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-07-25_ideas_have_levels", "19ad66ca57a036c8ed22f51c75a62507");
        context.beforeTest();

        // # Ideas Have Levels                                                                              // # Ideas Have Levels

        // ## Increasing XP                                                                                 // ## Increasing XP
        context.enterTheGame();                                                                             // * Enter the game.
        context.thereShouldBeTheSIdea("Harvest Idea");                                                      // * There should be the "Harvest Idea" idea.
        context.theSShouldHaveLevelNAndNXp("Harvest Idea", 1, 0);                                           // * The "Harvest Idea" should have level 1 and 0 XP.
        context.drawACardFromTheSIdea("Harvest Idea");                                                      // * Draw a card from the "Harvest Idea" idea.
        context.moveTheSCardToItsOwnStack("Harvest Idea");                                                  // * Move the "Harvest Idea" card to its own stack.
        context.moveTheSCardOnTopOfTheSCard("Villager", "Harvest Idea");                                    // * Move the "Villager" card on top of the "Harvest Idea" card.
        context.moveTheSCardOnTopOfTheSCard("Berry Bush", "Villager");                                      // * Move the "Berry Bush" card on top of the "Villager" card.
        context.thereShouldBeNStacksOfNSNSAndNSCards(1, 1, "Harvest Idea", 1, "Villager", 1, "Berry Bush"); // * There should be 1 stacks of 1 "Harvest Idea", 1 "Villager", and 1 "Berry Bush" cards.
        context.thereShouldBeNSCards(1, "Berry");                                                           // * There should be 1 "Berry" cards.
        context.theSShouldHaveLevelNAndNXp("Harvest Idea", 1, 0);                                           // * The "Harvest Idea" should have level 1 and 0 XP.
        context.endTheCurrentMoon();                                                                        // * End the current moon.
        context.theSShouldHaveLevelNAndNXp("Harvest Idea", 1, 1);                                           // * The "Harvest Idea" should have level 1 and 1 XP.
        context.thereShouldBeNSCards(2, "Berry");                                                           // * There should be 2 "Berry" cards.
        // ### Gaining several XP at once                                                                   // ### Gaining several XP at once
        context.givenANewGame();                                                                            // * Given a new game.
        context.givenThereIsTheSIdea("Harvest Idea");                                                       // * Given there is the "Harvest Idea" idea.
        context.givenThereAreNSCards(2, "Berry");                                                           // * Given there are 2 "Berry" cards.
        context.givenThereAreNStacksOfNSNSAndNSCards(2, 1, "Harvest Idea", 1, "Villager", 1, "Berry Bush"); // * Given there are 2 stacks of 1 "Harvest Idea", 1 "Villager", and 1 "Berry Bush" cards.
        context.theSShouldHaveLevelNAndNXp("Harvest Idea", 1, 0);                                           // * The "Harvest Idea" should have level 1 and 0 XP.
        context.endTheCurrentMoon();                                                                        // * End the current moon.
        context.theSShouldHaveLevelNAndNXp("Harvest Idea", 1, 2);                                           // * The "Harvest Idea" should have level 1 and 2 XP.

        // ## Increasing level                                                                              // ## Increasing level
        context.givenANewGame();                                                                            // * Given a new game.
        context.givenThereIsTheSIdeaAtLevelNAndNXp("Harvest Idea", 1, 9);                                   // * Given there is the "Harvest Idea" idea at level 1 and 9 XP.
        context.givenThereAreNSCards(1, "Berry");                                                           // * Given there are 1 "Berry" cards.
        context.givenThereAreNStacksOfNSNSAndNSCards(1, 1, "Harvest Idea", 1, "Villager", 1, "Berry Bush"); // * Given there are 1 stacks of 1 "Harvest Idea", 1 "Villager", and 1 "Berry Bush" cards.
        context.endTheCurrentMoon();                                                                        // * End the current moon.
        context.theSShouldHaveLevelNAndNXp("Harvest Idea", 2, 0);                                           // * The "Harvest Idea" should have level 2 and 0 XP.
        context.thereShouldBeNSCards(3, "Berry");                                                           // * There should be 3 "Berry" cards.
        // ### Increasing more levels                                                                       // ### Increasing more levels
        // #### | $PreviousLevel |  $XPThreshold |  $NextLevel | $NextBerries |                             // #### | $PreviousLevel |  $XPThreshold |  $NextLevel | $NextBerries |
        // #### |---------------:|--------------:|------------:|-------------:|                             // #### |---------------:|--------------:|------------:|-------------:|
        // #### |              1 |             9 |           2 |            3 |                             // #### |              1 |             9 |           2 |            3 |
        context.givenANewGameWithNSProductionStack(1, "Berry Bush");                                        // * Given a new game with 1 "Berry Bush" production stack.
        context.givenThereIsTheSIdeaAtLevelNAndNXp("Harvest Idea", 1, 9);                                   // * Given there is the "Harvest Idea" idea at level 1 and 9 XP.
        context.endTheCurrentMoon();                                                                        // * End the current moon.
        // #### And result                                                                                  // #### And result
        context.theSShouldHaveLevelNAndNXp("Harvest Idea", 2, 0);                                           // * The "Harvest Idea" should have level 2 and 0 XP.
        context.thereShouldBeNSCards(3, "Berry");                                                           // * There should be 3 "Berry" cards.
        // ### Increasing more levels                                                                       // ### Increasing more levels
        // #### | $PreviousLevel |  $XPThreshold |  $NextLevel | $NextBerries |                             // #### | $PreviousLevel |  $XPThreshold |  $NextLevel | $NextBerries |
        // #### |---------------:|--------------:|------------:|-------------:|                             // #### |---------------:|--------------:|------------:|-------------:|
        // #### |              2 |            19 |           3 |            4 |                             // #### |              2 |            19 |           3 |            4 |
        context.givenANewGameWithNSProductionStack(1, "Berry Bush");                                        // * Given a new game with 1 "Berry Bush" production stack.
        context.givenThereIsTheSIdeaAtLevelNAndNXp("Harvest Idea", 2, 19);                                  // * Given there is the "Harvest Idea" idea at level 2 and 19 XP.
        context.endTheCurrentMoon();                                                                        // * End the current moon.
        // #### And result                                                                                  // #### And result
        context.theSShouldHaveLevelNAndNXp("Harvest Idea", 3, 0);                                           // * The "Harvest Idea" should have level 3 and 0 XP.
        context.thereShouldBeNSCards(4, "Berry");                                                           // * There should be 4 "Berry" cards.
        // ### Increasing more levels                                                                       // ### Increasing more levels
        // #### | $PreviousLevel |  $XPThreshold |  $NextLevel | $NextBerries |                             // #### | $PreviousLevel |  $XPThreshold |  $NextLevel | $NextBerries |
        // #### |---------------:|--------------:|------------:|-------------:|                             // #### |---------------:|--------------:|------------:|-------------:|
        // #### |              3 |            29 |           4 |            5 |                             // #### |              3 |            29 |           4 |            5 |
        context.givenANewGameWithNSProductionStack(1, "Berry Bush");                                        // * Given a new game with 1 "Berry Bush" production stack.
        context.givenThereIsTheSIdeaAtLevelNAndNXp("Harvest Idea", 3, 29);                                  // * Given there is the "Harvest Idea" idea at level 3 and 29 XP.
        context.endTheCurrentMoon();                                                                        // * End the current moon.
        // #### And result                                                                                  // #### And result
        context.theSShouldHaveLevelNAndNXp("Harvest Idea", 4, 0);                                           // * The "Harvest Idea" should have level 4 and 0 XP.
        context.thereShouldBeNSCards(5, "Berry");                                                           // * There should be 5 "Berry" cards.
        // ### Increasing more levels                                                                       // ### Increasing more levels
        // #### | $PreviousLevel |  $XPThreshold |  $NextLevel | $NextBerries |                             // #### | $PreviousLevel |  $XPThreshold |  $NextLevel | $NextBerries |
        // #### |---------------:|--------------:|------------:|-------------:|                             // #### |---------------:|--------------:|------------:|-------------:|
        // #### |              4 |            39 |           5 |            6 |                             // #### |              4 |            39 |           5 |            6 |
        context.givenANewGameWithNSProductionStack(1, "Berry Bush");                                        // * Given a new game with 1 "Berry Bush" production stack.
        context.givenThereIsTheSIdeaAtLevelNAndNXp("Harvest Idea", 4, 39);                                  // * Given there is the "Harvest Idea" idea at level 4 and 39 XP.
        context.endTheCurrentMoon();                                                                        // * End the current moon.
        // #### And result                                                                                  // #### And result
        context.theSShouldHaveLevelNAndNXp("Harvest Idea", 5, 0);                                           // * The "Harvest Idea" should have level 5 and 0 XP.
        context.thereShouldBeNSCards(6, "Berry");                                                           // * There should be 6 "Berry" cards.
        // ### Increasing more levels                                                                       // ### Increasing more levels
        // #### | $PreviousLevel |  $XPThreshold |  $NextLevel | $NextBerries |                             // #### | $PreviousLevel |  $XPThreshold |  $NextLevel | $NextBerries |
        // #### |---------------:|--------------:|------------:|-------------:|                             // #### |---------------:|--------------:|------------:|-------------:|
        // #### |              5 |            49 |           6 |            7 |                             // #### |              5 |            49 |           6 |            7 |
        context.givenANewGameWithNSProductionStack(1, "Berry Bush");                                        // * Given a new game with 1 "Berry Bush" production stack.
        context.givenThereIsTheSIdeaAtLevelNAndNXp("Harvest Idea", 5, 49);                                  // * Given there is the "Harvest Idea" idea at level 5 and 49 XP.
        context.endTheCurrentMoon();                                                                        // * End the current moon.
        // #### And result                                                                                  // #### And result
        context.theSShouldHaveLevelNAndNXp("Harvest Idea", 6, 0);                                           // * The "Harvest Idea" should have level 6 and 0 XP.
        context.thereShouldBeNSCards(7, "Berry");                                                           // * There should be 7 "Berry" cards.
        // ### XP are not lost                                                                              // ### XP are not lost
        context.givenANewGameWithNSProductionStack(3, "Berry Bush");                                        // * Given a new game with 3 "Berry Bush" production stack.
        context.givenThereIsTheSIdeaAtLevelNAndNXp("Harvest Idea", 1, 9);                                   // * Given there is the "Harvest Idea" idea at level 1 and 9 XP.
        context.endTheCurrentMoon();                                                                        // * End the current moon.
        context.theSShouldHaveLevelNAndNXp("Harvest Idea", 2, 2);                                           // * The "Harvest Idea" should have level 2 and 2 XP.

        // ## New ideas from existing ideas                                                                 // ## New ideas from existing ideas
        context.givenANewGameWithNSProductionStack(1, "Berry Bush");                                        // * Given a new game with 1 "Berry Bush" production stack.
        context.givenThereIsTheSIdeaAtLevelNAndNXp("Harvest Idea", 1, 9);                                   // * Given there is the "Harvest Idea" idea at level 1 and 9 XP.
        context.thereShouldBeNoSIdea("Seed Idea");                                                          // * There should be no "Seed Idea" idea.
        context.endTheCurrentMoon();                                                                        // * End the current moon.
        context.theSShouldHaveLevelNAndNXp("Harvest Idea", 2, 0);                                           // * The "Harvest Idea" should have level 2 and 0 XP.
        context.thereShouldBeTheSIdea("Seed Idea");                                                         // * There should be the "Seed Idea" idea.
        context.theSShouldHaveLevelNAndNXp("Seed Idea", 1, 0);                                              // * The "Seed Idea" should have level 1 and 0 XP.
        // ### Do not lose old XP gaining again                                                             // ### Do not lose old XP gaining again
        context.givenANewGameWithNSProductionStack(1, "Berry Bush");                                        // * Given a new game with 1 "Berry Bush" production stack.
        context.givenThereIsTheSIdeaAtLevelNAndNXp("Harvest Idea", 1, 9);                                   // * Given there is the "Harvest Idea" idea at level 1 and 9 XP.
        context.givenThereIsTheSIdeaAtLevelNAndNXp("Seed Idea", 3, 12);                                     // * Given there is the "Seed Idea" idea at level 3 and 12 XP.
        context.endTheCurrentMoon();                                                                        // * End the current moon.
        context.theSShouldHaveLevelNAndNXp("Harvest Idea", 2, 0);                                           // * The "Harvest Idea" should have level 2 and 0 XP.
        context.theSShouldHaveLevelNAndNXp("Seed Idea", 3, 12);                                             // * The "Seed Idea" should have level 3 and 12 XP.

        // ## Ideas may take several moons.                                                                 // ## Ideas may take several moons.
        context.givenANewGame();                                                                            // * Given a new game.
        context.givenThereIsTheSIdeaAtLevelNAndNXp("Seed Idea", 1, 0);                                      // * Given there is the "Seed Idea" idea at level 1 and 0 XP.
        context.givenThereAreNStacksOfNSCards(1, 5, "Berry");                                               // * Given there are 1 stacks of 5 "Berry" cards.
        context.givenThereAreNStacksOfNSNSAndNSCards(1, 1, "Seed Idea", 1, "Villager", 1, "Berry");         // * Given there are 1 stacks of 1 "Seed Idea", 1 "Villager", and 1 "Berry" cards.
        context.givenThereAreNSCards(0, "Berry Bush");                                                      // * Given there are 0 "Berry Bush" cards.
        context.endTheCurrentMoon();                                                                        // * End the current moon.
        context.theSIdeaShouldRequireNCardWithAtLeastNInSTag("Seed Idea", 1, 1, "Seed");                    // * The "Seed Idea" idea should require 1 card with at least 1 in "Seed" tag.
        context.theSIdeaShouldRequireNCardWithAtLeastNInSTag("Seed Idea", 1, 1, "Worker");                  // * The "Seed Idea" idea should require 1 card with at least 1 in "Worker" tag.
        context.theSCardShouldHaveNInSTag("Berry", 1, "Seed");                                              // * The "Berry" card should have 1 in "Seed" tag.
        context.theSCardDescriptionShouldSaySIsS("Berry", "Plant", "Berry Bush");                           // * The "Berry" card description should say "Plant" is "Berry Bush".
        context.theSShouldHaveLevelNAndNXp("Seed Idea", 1, 0);                                              // * The "Seed Idea" should have level 1 and 0 XP.
        context.thereShouldBeNSCards(0, "Berry Bush");                                                      // * There should be 0 "Berry Bush" cards.
        context.theSCardProgressShouldBeNOfN("Seed Idea", 1, 5);                                            // * The "Seed Idea" card progress should be 1 of 5.
        context.endTheCurrentMoon();                                                                        // * End the current moon.
        context.theSCardProgressShouldBeNOfN("Seed Idea", 2, 5);                                            // * The "Seed Idea" card progress should be 2 of 5.
        context.endTheCurrentMoon();                                                                        // * End the current moon.
        context.theSCardProgressShouldBeNOfN("Seed Idea", 3, 5);                                            // * The "Seed Idea" card progress should be 3 of 5.
        context.endTheCurrentMoon();                                                                        // * End the current moon.
        context.theSCardProgressShouldBeNOfN("Seed Idea", 4, 5);                                            // * The "Seed Idea" card progress should be 4 of 5.
        context.theSShouldHaveLevelNAndNXp("Seed Idea", 1, 0);                                              // * The "Seed Idea" should have level 1 and 0 XP.
        context.thereShouldBeNSCards(0, "Berry Bush");                                                      // * There should be 0 "Berry Bush" cards.
        context.theSCardProgressShouldBeNOfN("Seed Idea", 4, 5);                                            // * The "Seed Idea" card progress should be 4 of 5.
        context.endTheCurrentMoon();                                                                        // * End the current moon.
        context.theSCardProgressShouldBeNOfN("Seed Idea", 0, 5);                                            // * The "Seed Idea" card progress should be 0 of 5.
        context.theSShouldHaveLevelNAndNXp("Seed Idea", 1, 1);                                              // * The "Seed Idea" should have level 1 and 1 XP.
        context.thereShouldBeNSCards(1, "Berry Bush");                                                      // * There should be 1 "Berry Bush" cards.
        context.givenANewGame();                                                                            // * Given a new game.
        context.givenThereIsTheSIdeaAtLevelNAndNXp("Seed Idea", 1, 0);                                      // * Given there is the "Seed Idea" idea at level 1 and 0 XP.
        context.givenThereAreNStacksOfNSCards(1, 5, "Berry");                                               // * Given there are 1 stacks of 5 "Berry" cards.
        context.givenThereAreNStacksOfNSNSAndNSCards(1, 1, "Seed Idea", 1, "Villager", 1, "Apple");         // * Given there are 1 stacks of 1 "Seed Idea", 1 "Villager", and 1 "Apple" cards.
        context.givenThereAreNSCards(0, "Apple Tree");                                                      // * Given there are 0 "Apple Tree" cards.
        context.theSCardShouldHaveNInSTag("Apple", 1, "Seed");                                              // * The "Apple" card should have 1 in "Seed" tag.
        context.theSCardDescriptionShouldSaySIsS("Apple", "Plant", "Apple Tree");                           // * The "Apple" card description should say "Plant" is "Apple Tree".
        context.endTheCurrentMoon();                                                                        // * End the current moon.
        context.endTheCurrentMoon();                                                                        // * End the current moon.
        context.endTheCurrentMoon();                                                                        // * End the current moon.
        context.endTheCurrentMoon();                                                                        // * End the current moon.
        context.endTheCurrentMoon();                                                                        // * End the current moon.
        context.thereShouldBeNSCards(1, "Apple Tree");                                                      // * There should be 1 "Apple Tree" cards.
        context.givenANewGame();                                                                            // * Given a new game.
        context.givenThereIsTheSIdeaAtLevelNAndNXp("Harvest Idea", 1, 0);                                   // * Given there is the "Harvest Idea" idea at level 1 and 0 XP.
        context.givenThereAreNStacksOfNSCards(1, 1, "Berry");                                               // * Given there are 1 stacks of 1 "Berry" cards.
        context.givenThereAreNStacksOfNSNSAndNSCards(1, 1, "Harvest Idea", 1, "Villager", 1, "Apple Tree"); // * Given there are 1 stacks of 1 "Harvest Idea", 1 "Villager", and 1 "Apple Tree" cards.
        context.endTheCurrentMoon();                                                                        // * End the current moon.
        context.thereShouldBeNSCards(1, "Apple Tree");                                                      // * There should be 1 "Apple Tree" cards.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
