package com.drpicox.game.idea;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221020_BuildIdea_Test {

    @Autowired Post_20221020_BuildIdea_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-10-20_build_idea", "5c6e1a585916f721b96d2ff101aa92ab");
        context.beforeTest();

        // # Build idea                                                                                             // # Build idea

        // ## How to acquire:                                                                                       // ## How to acquire:
        context.givenANewGameWithAStackOfNSCardsNSCardAndNSCard(1, "Harvest Idea", 1, "Villager", 1, "Berry Bush"); // * Given a new game with a stack of 1 "Harvest Idea" cards, 1 "Villager" card and 1 "Berry Bush" card..
        context.givenThereIsTheSIdeaAtLevelNAndNXp("Harvest Idea", 2, 19);                                          // * Given there is the "Harvest Idea" idea at level 2 and 19 XP.
        context.thereShouldBeNoSIdea("Build Idea");                                                                 // * There should be no "Build Idea" idea.
        context.endTheCurrentMoon();                                                                                // * End the current moon.
        context.theSShouldHaveLevelNAndNXp("Harvest Idea", 3, 0);                                                   // * The "Harvest Idea" should have level 3 and 0 XP.
        context.thereShouldBeTheSIdea("Build Idea");                                                                // * There should be the "Build Idea" idea.
        context.theSShouldHaveLevelNAndNXp("Build Idea", 1, 0);                                                     // * The "Build Idea" should have level 1 and 0 XP.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
