package com.drpicox.game.idea;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221110_OldVillageStrollIdea_Test {

    @Autowired Post_20221110_OldVillageStrollIdea_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-11-10_old_village_stroll_idea", "0629ced3be65af5295886c52ab85a61d");
        context.beforeTest();

        // # Old Village Stroll idea                                                        // # Old Village Stroll idea

        // ## How to get old village stroll idea?                                           // ## How to get old village stroll idea?
        context.givenANewGameWithAStackOfNSCardsAndNSCard(1, "Old Village", 1, "Villager"); // * Given a new game with a stack of 1 "Old Village" cards and 1 "Villager" card.
        context.endTheCurrentMoon();                                                        // * End the current moon.
        context.thereShouldBeTheSIdea("Old Village Stroll Idea");                           // * There should be the "Old Village Stroll Idea" idea.
        context.theSShouldHaveLevelNAndNXp("Old Village Stroll Idea", 1, 0);                // * The "Old Village Stroll Idea" should have level 1 and 0 XP.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
