package com.drpicox.game.animal;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221128_Grizzly_Test {

    @Autowired Post_20221128_Grizzly_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-11-28_grizzly", "22c532dfe57167a606c77e3b32dca4c4");
        context.beforeTest();

        // # Grizzly!                                                                                                                                                   // # Grizzly!

        // ## How to find a Grizzly?                                                                                                                                    // ## How to find a Grizzly?
        context.givenANewGameWithAStackOfNSNSNSCardsAndNS(1, "Snowy Mountain Stroll Idea", 1, "Snowy Mountain", 1, "Villager", 1, "Mountain Kit");                      // * Given a new game with a stack of 1 "Snowy Mountain Stroll Idea", 1 "Snowy Mountain", 1 "Villager" cards and 1 "Mountain Kit".
        context.givenThereIsTheSIdeaAtLevelNAndNXp("Snowy Mountain Stroll Idea", 1, 0);                                                                                 // * Given there is the "Snowy Mountain Stroll Idea" idea at level 1 and 0 XP.
        context.theSMayCreateASCard("Snowy Mountain Stroll Idea", "Grizzly");                                                                                           // * The "Snowy Mountain Stroll Idea" may create a "Grizzly" card.
        context.endTheCurrentMoon();                                                                                                                                    // * End the current moon.
        context.thereShouldBeNStacksOfNSNSNSNSCardsAndNSCards(1, 1, "Snowy Mountain Stroll Idea", 1, "Snowy Mountain", 1, "Villager", 1, "Mountain Kit", 1, "Grizzly"); // * There should be 1 stacks of 1 "Snowy Mountain Stroll Idea", 1 "Snowy Mountain", 1 "Villager", 1 "Mountain Kit" cards and 1 "Grizzly" cards.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
