package com.drpicox.game.animal;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20220913_KillingWolf_Test {

    @Autowired Post_20220913_KillingWolf_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-09-13_killing_wolf", "5f4f5d4cc2b02c6322954ac2c919528b");
        context.beforeTest();

        // # Killing Wolf                           // # Killing Wolf

        // ## How to kill a wolf?                   // ## How to kill a wolf?
        context.givenThereAreNSCards(1, "Militia"); // * Given there are 1 "Militia" cards.
        context.givenThereAreNSCards(1, "Wolf");    // * Given there are 1 "Wolf" cards.
        context.endTheCurrentMoon();                // * End the current moon.
        context.thereShouldBeNSCards(0, "Wolf");    // * There should be 0 "Wolf" cards.
        context.thereShouldBeNSCards(1, "Militia"); // * There should be 1 "Militia" cards.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
