package com.drpicox.game.animal;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221207_HunterKillGrizzly_Test {

    @Autowired Post_20221207_HunterKillGrizzly_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-12-07_hunter_kill_grizzly", "f4aff42e8c0f7eb805c5b102e399c523");
        context.beforeTest();

        // # Hunter Kill Grizzly                    // # Hunter Kill Grizzly

        // ## How to kill a Grizzly?                // ## How to kill a Grizzly?
        context.givenThereAreNSCards(1, "Hunter");  // * Given there are 1 "Hunter" cards.
        context.givenThereAreNSCards(1, "Grizzly"); // * Given there are 1 "Grizzly" cards.
        context.endTheCurrentMoon();                // * End the current moon.
        context.thereShouldBeNSCards(0, "Grizzly"); // * There should be 0 "Grizzly" cards.
        context.thereShouldBeNSCards(1, "Hunter");  // * There should be 1 "Hunter" cards.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
