package com.drpicox.game.animal;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221114_Chicken_Test {

    @Autowired Post_20221114_Chicken_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-11-14_chicken", "64b073998c6621182178a84ce83c5065");
        context.beforeTest();

        // # Chicken                                                                                          // # Chicken

        // ## How to find a Chicken                                                                           // ## How to find a Chicken
        context.givenANewGameWithAStackOfNSCardsAndNSCards(1, "Woods Stroll Idea", 1, "Villager");            // * Given a new game with a stack of 1 "Woods Stroll Idea" cards and 1 "Villager" cards.
        context.givenThereIsTheSIdeaAtLevelNAndNXp("Woods Stroll Idea", 4, 0);                                // * Given there is the "Woods Stroll Idea" idea at level 4 and 0 XP.
        context.theSMayCreateASCard("Woods Stroll Idea", "Chicken");                                          // * The "Woods Stroll Idea" may create a "Chicken" card.
        context.givenThatTheOddsAreThatWeWillGetASFromTheSCard("Chicken", "Woods Stroll Idea");               // * Given that the odds are that we will get a "Chicken" from the "Woods Stroll Idea" card.
        context.endTheCurrentMoon();                                                                          // * End the current moon.
        context.thereShouldBeNStacksOfNSNSAndNSCards(1, 1, "Woods Stroll Idea", 1, "Villager", 1, "Chicken"); // * There should be 1 stacks of 1 "Woods Stroll Idea", 1 "Villager" and 1 "Chicken" cards.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
