package com.drpicox.game.animal;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221120_ChickenLaysEgg_Test {

    @Autowired Post_20221120_ChickenLaysEgg_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-11-20_chicken_lays_egg", "9b301b1f2060b2ad422f7804d8893ab8");
        context.beforeTest();

        // # Chicken lays egg                                                  // # Chicken lays egg

        // ## How a chicken lays an egg                                        // ## How a chicken lays an egg
        context.givenThereAreNSCards(1, "Chicken");                            // * Given there are 1 "Chicken" cards.
        context.endTheCurrentMoon();                                           // * End the current moon.
        context.thereShouldBeNStacksOfNSAndNSCards(1, 1, "Chicken", 1, "Egg"); // * There should be 1 stacks of 1 "Chicken" and 1 "Egg" cards.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
