package com.drpicox.game.animal;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221103_Creeper_Test {

    @Autowired Post_20221103_Creeper_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-11-03_creeper", "9a7221075471ff734bb5b8bef4fca64c");
        context.beforeTest();

        // # Creeper!                                                                                              // # Creeper!

        // ## How to find a creeper?                                                                               // ## How to find a creeper?
        context.givenANewGameWithAStackOfNSCardsAndNSCard(1, "Woods Stroll Idea", 1, "Villager");                  // * Given a new game with a stack of 1 "Woods Stroll Idea" cards and 1 "Villager" card.
        context.givenThereIsTheSIdeaAtLevelNAndNXp("Woods Stroll Idea", 5, 0);                                     // * Given there is the "Woods Stroll Idea" idea at level 5 and 0 XP.
        context.theSMayCreateASCard("Woods Stroll Idea", "Creeper");                                               // * The "Woods Stroll Idea" may create a "Creeper" card.
        context.givenThatTheOddsAreThatWeWillFindASCardFromTheSCard("Creeper", "Woods Stroll Idea");               // * Given that the odds are that we will find a "Creeper" card from the "Woods Stroll Idea" card.
        context.endTheCurrentMoon();                                                                               // * End the current moon.
        context.thereShouldBeNStacksOfNSNSCardsAndNSCards(1, 1, "Woods Stroll Idea", 1, "Villager", 1, "Creeper"); // * There should be 1 stacks of 1 "Woods Stroll Idea", 1 "Villager" cards and 1 "Creeper" cards.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
