package com.drpicox.game.animal;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221117_FriendlyWolfKillWolf_Test {

    @Autowired Post_20221117_FriendlyWolfKillWolf_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-11-17_friendly_wolf_kill_wolf", "49c8b7a6df6ebf664d2905224c5d6ef3");
        context.beforeTest();

        // # Friendly Wolf Kill Wolf!                                                      // # Friendly Wolf Kill Wolf!
        // # How friendly wolf kills wolf?                                                 // # How friendly wolf kills wolf?
        context.givenANewGameWithAStackOfNSCardsAndNSCards(1, "Friendly Wolf", 1, "Wolf"); // * Given a new game with a stack of 1 "Friendly Wolf" cards and 1 "Wolf" cards.
        context.endTheCurrentMoon();                                                       // * End the current moon.
        context.thereShouldBeNSCards(0, "Friendly Wolf");                                  // * There should be 0 "Friendly Wolf" cards.
        context.thereShouldBeNSCards(0, "Wolf");                                           // * There should be 0 "Wolf" cards.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
