package com.drpicox.game.animal;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221020_FriendlyWolf_Test {

    @Autowired Post_20221020_FriendlyWolf_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-10-20_friendly_wolf", "f7d4eb1fc14cfc30caf8c87cb1e9dc81");
        context.beforeTest();

        // # Friendly Wolf!                                                              // # Friendly Wolf!

        // ## How to turn a wolf into a friendly wolf?                                   // ## How to turn a wolf into a friendly wolf?
        context.givenAStackOfNSNSAndNS(1, "Wolf", 1, "Villager", 1, "Bone");             // * Given a stack of 1 "Wolf", 1 "Villager" and 1 "Bone".
        context.givenThatTheOddsAreThatWeWillGetASFromTheSCard("Friendly Wolf", "Wolf"); // * Given that the odds are that we will get a "Friendly Wolf" from the "Wolf" card.
        context.endTheCurrentMoon();                                                     // * End the current moon.
        context.thereShouldBeNSCard(0, "Wolf");                                          // * There should be 0 "Wolf" card.
        context.thereShouldBeNSCard(0, "Bone");                                          // * There should be 0 "Bone" card.
        context.thereShouldBeNStackOfNSAndNS(1, 1, "Villager", 1, "Friendly Wolf");      // * There should be 1 stack of 1 "Villager" and 1 "Friendly Wolf"

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
