const path = require("node:path");
const { outputFile } = require("fs-extra");
const { join } = require("./join");
const { writeTestContextCalls } = require("./writeTestContextCalls");

async function writeJavaTestFile(post) {
  const testContent = await makeTestContent(post);

  await outputFile(
    path.join(
      "src",
      "test",
      "java",
      "com",
      "drpicox",
      "game",
      ...post.subPath,
      post.testName + ".java",
    ),
    testContent,
  );

  return true;
}
exports.writeJavaTestFile = writeJavaTestFile;

async function makeTestContent(post) {
  let testContent = ``;
  testContent += makeTestHeader(post);
  testContent += makeTestBody(post);
  testContent += makeTestFooter();

  return testContent;
}

function makeTestHeader(post) {
  const idValue = JSON.stringify(post.id);
  const md5Value = JSON.stringify(post.md5);

  return join(
    `package com.drpicox.game${post.subPackage};`,
    ``,
    `import org.junit.jupiter.api.Test;`,
    `import org.springframework.beans.factory.annotation.Autowired;`,
    `import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;`,
    `import org.springframework.boot.test.context.SpringBootTest;`,
    `import org.springframework.test.context.ActiveProfiles;`,
    ``,
    `import com.drpicox.game.util.TestUtils;`,
    ``,
    `// !!! IMPORTANT !!!`,
    `// This test file is AUTOGENERATED by yarn create-tests`,
    `// If you need to update it, run yarn create-tests`,
    `// DO NOT MODIFY manually. Keep running yarn create-tests instead,`,
    `// while editing your posts.`,
    ``,
    `@ActiveProfiles("test")`,
    `@SpringBootTest`,
    `@AutoConfigureMockMvc`,
    `public class ${post.testName} {`,
    ``,
    `    @Autowired ${post.contextName} context;`,
    `    @Autowired TestUtils testUtils;`,
    ``,
    `    @Test public void testPost() throws Throwable {`,
    `        testUtils.runBeforeTestStarts(${idValue}, ${md5Value});`,
    `        context.beforeTest();`,
    ``,
  );
}

function makeTestFooter() {
  return join(
    ``,
    `        context.afterTest();`,
    `        testUtils.runWhenTestSuccessful();`,
    `    }`,
    ``,
    `}`,
  );
}

const javaHandler = {
  indent: "        ",
  debug(text) {
    return `System.out.println(${JSON.stringify(text)});`;
  },
};

function makeTestBody(post) {
  return join(writeTestContextCalls(post, javaHandler));
}
