package com.drpicox.game.building;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221109_BreedFish_Test {

    @Autowired Post_20221109_BreedFish_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-11-09_breed_fish", "d7a613d249d85ae7c3a1e60724262a58");
        context.beforeTest();

        // # breed fish                                                                        // # breed fish

        // ## how to bread fish                                                                // ## how to bread fish
        context.givenANewGame();                                                               // * Given a new game.
        context.givenAStackOfNSAndNSCards(1, "Villager", 1, "Fish Farm");                      // * Given a stack of 1 "Villager" and 1 "Fish Farm" cards.
        context.endTheCurrentMoon();                                                           // * End the current moon.
        context.endTheCurrentMoon();                                                           // * End the current moon.
        context.thereShouldBeAStackOfNSNSAndNSCards(1, "Villager", 1, "Fish Farm", 1, "Fish"); // * There should be a stack of 1 "Villager", 1 "Fish Farm" and 1 "Fish" cards.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
