package com.drpicox.game.building;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221023_Barracks_Test {

    @Autowired Post_20221023_Barracks_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-10-23_barracks", "3e3f752bf0671320c716f33bb10a5e0b");
        context.beforeTest();

        // # Barracks                                                                                                            // # Barracks

        // ## How to build barracks                                                                                              // ## How to build barracks
        context.givenANewGameWithAStackOfNSCardsAndNSCardsAndNSCardsAndNSCards(1, "Villager", 3, "Wood", 3, "Stone", 2, "Iron"); // * Given a new game with a stack of 1 "Villager" cards and 3 "Wood" cards and 3 "Stone" cards and 2 "Iron" cards.
        context.endTheCurrentMoon();                                                                                             // * End the current moon.
        context.thereShouldBeNStacksOfNSCards(1, 1, "Barracks");                                                                 // * There should be 1 stacks of 1 "Barracks" cards

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
