package com.drpicox.game.building;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221013_StoneHouse_Test {

    @Autowired Post_20221013_StoneHouse_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-10-13_stone_house", "8dc20c7970bb4e9fb0bcd4892749816f");
        context.beforeTest();

        // # Stone House                                                                                       // # Stone House

        // ## How to build a Stone House                                                                       // ## How to build a Stone House
        context.givenANewGameWithAStackOfNSCardsNSCardsAndNSCards(1, "Build Idea", 1, "Villager", 4, "Stone"); // * Given a new game with a stack of 1 "Build Idea" cards, 1 "Villager" cards and 4 "Stone" cards
        context.endTheCurrentMoon();                                                                           // * End the current moon.
        context.thereShouldBeNStacksOfNSCardsNSCards(1, 1, "Build Idea", 1, "Villager");                       // * There should be 1 stacks of 1 "Build Idea" cards, 1 "Villager" cards
        context.thereShouldBeNStackOfNSCards(1, 1, "Stone House");                                             // * There should be 1 stack of 1 "Stone House" cards

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
