package com.drpicox.game.enemy;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221117_MilitiaKillCreeper_Test {

    @Autowired Post_20221117_MilitiaKillCreeper_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-11-17_militia_kill_creeper", "a4929e8c0f27886913e7c8fa046331aa");
        context.beforeTest();

        // # Militia Kill creeper                   // # Militia Kill creeper

        // ## How to kill a creeper?                // ## How to kill a creeper?
        context.givenThereAreNSCards(1, "Militia"); // * Given there are 1 "Militia" cards.
        context.givenThereAreNSCards(1, "Creeper"); // * Given there are 1 "Creeper" cards.
        context.endTheCurrentMoon();                // * End the current moon.
        context.thereShouldBeNSCards(0, "Creeper"); // * There should be 0 "Creeper" cards.
        context.thereShouldBeNSCards(1, "Militia"); // * There should be 1 "Militia" cards.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
