package com.drpicox.game.enemy;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221129_DwarfKillTroll_Test {

    @Autowired Post_20221129_DwarfKillTroll_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-11-29_dwarf_kill_troll", "ba64ff9e0e01bb5e2e878895f0edb113");
        context.beforeTest();

        // # Dwarf Kill Troll                     // # Dwarf Kill Troll

        // ## How to kill a troll?                // ## How to kill a troll?
        context.givenThereAreNSCards(1, "Dwarf"); // * Given there are 1 "Dwarf" cards.
        context.givenThereAreNSCards(1, "Troll"); // * Given there are 1 "Troll" cards.
        context.endTheCurrentMoon();              // * End the current moon.
        context.thereShouldBeNSCards(0, "Troll"); // * There should be 0 "Troll" cards.
        context.thereShouldBeNSCards(1, "Dwarf"); // * There should be 1 "Dwarf" cards.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
