package com.drpicox.game.enemy;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221129_Mummy_Test {

    @Autowired Post_20221129_Mummy_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-11-29_mummy", "2f00fd7e84d8c4477a01d6fa0187ef54");
        context.beforeTest();

        // # Mummy                                                                                                            // # Mummy

        // ## How a Mummy appears?                                                                                            // ## How a Mummy appears?
        context.givenANewGameWithAStackOfNSNSAndNSCards(1, "Dessert Stroll Idea", 1, "Dessert", 1, "Villager");               // * Given a new game with a stack of 1 "Dessert Stroll Idea", 1 "Dessert" and 1 "Villager" cards.
        context.givenThereIsTheSIdeaAtLevelNAndNXp("Dessert Stroll Idea", 3, 0);                                              // * Given there is the "Dessert Stroll Idea" idea at level 3 and 0 XP.
        context.theSMayCreateASCard("Dessert Stroll Idea", "Mummy");                                                          // * The "Dessert Stroll Idea" may create a "Mummy" card.
        context.endTheCurrentMoon();                                                                                          // * End the current moon.
        context.thereShouldBeNStacksOfNSNSNSAndNSCards(1, 1, "Dessert Stroll Idea", 1, "Dessert", 1, "Villager", 1, "Mummy"); // * There should be 1 stacks of 1 "Dessert Stroll Idea", 1 "Dessert", 1 "Villager" and 1 "Mummy" cards.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
