package com.drpicox.game.enemy;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221207_DothrakiKillScorpion_Test {

    @Autowired Post_20221207_DothrakiKillScorpion_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-12-07_dothraki_kill_scorpion", "320ded55405babb1f677a83af2c8b4cd");
        context.beforeTest();

        // # Dothraki Kill Scorpion                  // # Dothraki Kill Scorpion

        // ## How to kill a Scorpion?                // ## How to kill a Scorpion?
        context.givenThereAreNSCards(1, "Dothraki"); // * Given there are 1 "Dothraki" cards.
        context.givenThereAreNSCards(1, "Scorpion"); // * Given there are 1 "Scorpion" cards.
        context.endTheCurrentMoon();                 // * End the current moon.
        context.thereShouldBeNSCards(0, "Scorpion"); // * There should be 0 "Scorpion" cards.
        context.thereShouldBeNSCards(1, "Dothraki"); // * There should be 1 "Dothraki" cards.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
