package com.drpicox.game.food;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221119_Meat_Test {

    @Autowired Post_20221119_Meat_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-11-19_meat", "d10fea36440d09ea93e414bfaee7f554");
        context.beforeTest();

        // # MEAT                                                                // # MEAT
        context.givenANewGameWithAStackOfNSAndNSCards(4, "Villager", 1, "Meat"); // * Given a new game with a stack of 4 "Villager" and 1 "Meat" cards
        context.theSumOfAllSTagsValueShouldBeN("Eats", 4);                       // * The sum of all "Eats" tags value should be 4.
        context.theSumOfAllSTagsValueShouldBeN("Food", 4);                       // * The sum of all "Food" tags value should be 4.
        context.endTheCurrentMoon();                                             // * End the current moon.
        context.thereShouldBeNSCards(4, "Villager");                             // * There should be 4 "Villager" cards.
        context.thereShouldBeNSCards(0, "Meat");                                 // * There should be 0 "Meat" cards.
        context.theSumOfAllSTagsValueShouldBeN("Eats", 4);                       // * The sum of all "Eats" tags value should be 4.
        context.theSumOfAllSTagsValueShouldBeN("Food", 0);                       // * The sum of all "Food" tags value should be 0.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
