package com.drpicox.game.food;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221103_Milk_Test {

    @Autowired Post_20221103_Milk_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-11-03_milk", "8b1794634ecfcc793ab1f19cd9f3c731");
        context.beforeTest();

        // # Milk                                                                            // # Milk

        // ## How to obtain milk from a cow                                                  // ## How to obtain milk from a cow
        context.givenANewGameWithAStackOfNSCardsAndNSCards(1, "Cow", 1, "Villager");         // * Given a new game with a stack of 1 "Cow" cards and 1 "Villager" cards.
        context.endTheCurrentMoon();                                                         // * End the current moon.
        context.thereShouldBeNStacksOfNSNSAndNSCards(1, 1, "Cow", 1, "Villager", 1, "Milk"); // * There should be 1 stacks of 1 "Cow", 1 "Villager" and 1 "Milk" cards.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
