package com.drpicox.game.food;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221120_Egg_Test {

    @Autowired Post_20221120_Egg_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-11-20_egg", "0ca6b31378734fdb924b6d7fed04ec24");
        context.beforeTest();

        // # Egg                                           // # Egg
        // ### Eating an Egg                               // ### Eating an Egg
        context.givenThereAreNSCards(1, "Egg");            // * Given there are 1 "Egg" cards.
        context.givenThereAreNSCards(1, "Villager");       // * Given there are 1 "Villager" cards.
        context.theSumOfAllSTagsValueShouldBeN("Eats", 1); // * The sum of all "Eats" tags value should be 1.
        context.theSumOfAllSTagsValueShouldBeN("Food", 1); // * The sum of all "Food" tags value should be 1.
        context.endTheCurrentMoon();                       // * End the current moon.
        context.thereShouldBeNSCards(1, "Villager");       // * There should be 1 "Villager" cards.
        context.thereShouldBeNSCards(0, "Egg");            // * There should be 0 "Egg" cards.
        context.theSumOfAllSTagsValueShouldBeN("Eats", 1); // * The sum of all "Eats" tags value should be 1.
        context.theSumOfAllSTagsValueShouldBeN("Food", 0); // * The sum of all "Food" tags value should be 0.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
