package com.drpicox.game.mineral;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221105_Flint_Test {

    @Autowired Post_20221105_Flint_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-11-05_flint", "25e18333dbff37a9b7408a67795eb2c5");
        context.beforeTest();

        // # FLINT                                                                                // # FLINT

        // ## HOW TO ACQUIRE FLINT                                                                // ## HOW TO ACQUIRE FLINT
        context.givenANewGameWithAStackOfNSNSAndNSCards(1, "Villager", 1, "Stone", 1, "Pickaxe"); // * Given a new game with a stack of 1 "Villager", 1 "Stone" and 1 "Pickaxe" cards
        context.endTheCurrentMoon();                                                              // * End the current moon
        context.thereShouldBeNStackOfNSNSAndNSCards(1, 1, "Villager", 1, "Pickaxe", 2, "Flint");  // * There should be 1 stack of 1 "Villager", 1 "Pickaxe" and 2 "Flint" cards

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
