package com.drpicox.game.mineral;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221013_Iron_Test {

    @Autowired Post_20221013_Iron_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-10-13_iron", "6516380e53f712f6df2d63f1393774c2");
        context.beforeTest();

        // # Iron                                                                                          // # Iron

        // ## How to obtain iron?                                                                          // ## How to obtain iron?
        context.givenANewGameWithAStackOfNSCardsAndNSCards(1, "Woods Stroll Idea", 1, "Villager");         // * Given a new game with a stack of 1 "Woods Stroll Idea" cards and 1 "Villager" cards.
        context.givenThereIsTheSIdeaAtLevelNAndNXp("Woods Stroll Idea", 3, 0);                             // * Given there is the "Woods Stroll Idea" idea at level 3 and 0 XP.
        context.theSMayCreateASCard("Woods Stroll Idea", "Iron");                                          // * The "Woods Stroll Idea" may create a "Iron" card.
        context.givenThatTheOddsAreThatWeWillGetASFromTheSCard("Iron", "Woods Stroll Idea");               // * Given that the odds are that we will get a "Iron" from the "Woods Stroll Idea" card.
        context.endTheCurrentMoon();                                                                       // * End the current moon.
        context.thereShouldBeNStacksOfNSNSAndNSCards(1, 1, "Woods Stroll Idea", 1, "Villager", 1, "Iron"); // * There should be 1 stacks of 1 "Woods Stroll Idea", 1 "Villager" and 1 "Iron" cards.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
