package com.drpicox.game.villager;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221105_Wizard_Test {

    @Autowired Post_20221105_Wizard_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-11-05_wizard", "d915933ad00253d9d2103d1dcd35deed");
        context.beforeTest();

        // # Wizard                                                                 // # Wizard

        // ## How to transform a Wizard?                                            // ## How to transform a Wizard?
        context.givenANewGameWithAStackOfNSNSCards(1, "Villager", 1, "Magic Book"); // * Given a new game with a stack of 1 "Villager", 1 "Magic Book" cards.
        context.endTheCurrentMoon();                                                // * End the current moon.
        context.thereShouldBeNStacksOfNSCards(1, 1, "Wizard");                      // * There should be 1 stacks of 1 "Wizard" cards

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
