package com.drpicox.game.villager;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221205_Dothraki_Test {

    @Autowired Post_20221205_Dothraki_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-12-05_dothraki", "b82646d22a67f47eee4d0b75977f4307");
        context.beforeTest();

        // # Dothraki                                                          // # Dothraki

        // ## How to transform a dothraki                                      // ## How to transform a dothraki
        context.givenANewGameWithAStackOfNSNSCards(1, "Villager", 1, "Arakh"); // * Given a new game with a stack of 1 "Villager", 1 "Arakh" cards.
        context.endTheCurrentMoon();                                           // * End the current moon.
        context.thereShouldBeNStacksOfNSCards(1, 1, "Dothraki");               // * There should be 1 stacks of 1 "Dothraki" cards

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
