package com.drpicox.game.villager;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221106_Archer_Test {

    @Autowired Post_20221106_Archer_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-11-06_archer", "84f7c8c409f4ab06efecc9fecf9867ef");
        context.beforeTest();

        // # Archer                                                          // # Archer

        // ## How to transform to archer                                     // ## How to transform to archer
        context.givenANewGameWithAStackOfNSNSCards(1, "Villager", 1, "Bow"); // * Given a new game with a stack of 1 "Villager", 1 "Bow" cards.
        context.endTheCurrentMoon();                                         // * End the current moon.
        context.thereShouldBeNStacksOfNSCards(1, 1, "Archer");               // * There should be 1 stacks of 1 "Archer" cards.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
