package com.drpicox.game.tool;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221031_FishingRod_Test {

    @Autowired Post_20221031_FishingRod_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-10-31_fishing_rod", "662ec1e9994e6645fb196d8c2f54b657");
        context.beforeTest();

        // # Fishing Rod                                                                                           // # Fishing Rod

        // ## How to create the fishing rod                                                                        // ## How to create the fishing rod
        context.givenANewGameWithAStackOfNSNSNSAndNSCards(1, "Build Idea", 1, "Villager", 2, "Wood", 1, "String"); // * Given a new game with a stack of 1 "Build Idea", 1 "Villager", 2 "Wood" and 1 "String" cards.
        context.endTheCurrentMoon();                                                                               // * End the current moon.
        context.thereShouldBeNStacksOfNSNSNSCards(1, 1, "Build Idea", 1, "Villager", 1, "Fishing Rod");            // * There should be 1 stacks of 1 "Build Idea", 1 "Villager", 1 "Fishing Rod" cards.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
