package com.drpicox.game.tool;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221128_MountainKit_Test {

    @Autowired Post_20221128_MountainKit_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-11-28_mountain_kit", "dfa6810322f0410979049dd6f2fdfafd");
        context.beforeTest();

        // # Mountain Kit                                                                                        // # Mountain Kit

        // ## How to create a Mountain Kit?                                                                      // ## How to create a Mountain Kit?
        context.givenANewGameWithAStackOfNSNSNSAndNS(1, "Build Idea", 1, "Villager", 1, "String", 1, "Leather"); // * Given a new game with a stack of 1 "Build Idea", 1 "Villager", 1 "String" and 1 "Leather".
        context.endTheCurrentMoon();                                                                             // * End the current moon.
        context.thereShouldBeNStacksOfNSNSAndNSCards(1, 1, "Build Idea", 1, "Villager", 1, "Mountain Kit");      // * There should be 1 stacks of 1 "Build Idea", 1 "Villager" and 1 "Mountain Kit" cards.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
