package com.drpicox.game.location;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221114_FindingMoreThingsInOldVillage_Test {

    @Autowired Post_20221114_FindingMoreThingsInOldVillage_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-11-14_finding_more_things_in_old_village", "fddba26e25bdabc2c59dc348547da5b6");
        context.beforeTest();

        // # Finding more things in Old Village                                                                                                 // # Finding more things in Old Village

        // ## | $CardName       |                                                                                                               // ## | $CardName       |

        // ## |-----------------|                                                                                                               // ## |-----------------|

        // ## | Berry           |                                                                                                               // ## | Berry           |
        context.givenANewGameWithAStackOfNSNSAndNSCards(1, "Old Village", 1, "Old Village Stroll Idea", 1, "Villager");                         // * Given a new game with a stack of 1 "Old Village", 1 "Old Village Stroll Idea" and 1 "Villager" cards.
        context.theSMayCreateASCard("Old Village Stroll Idea", "Berry");                                                                        // * The "Old Village Stroll Idea" may create a "Berry" card.
        context.givenThatTheOddsAreThatWeWillGetASFromTheSCard("Berry", "Old Village");                                                         // * Given that the odds are that we will get a "Berry" from the "Old Village" card.
        context.endTheCurrentMoon();                                                                                                            // * End the current moon.
        context.thereShouldBeNStacksOfNSNSNSAndNSCards(1, 1, "Old Village Stroll Idea", 1, "Old Village", 1, "Villager", 1, "Berry");           // * There should be 1 stacks of 1 "Old Village Stroll Idea", 1 "Old Village", 1 "Villager" and 1 "Berry" cards.
        // # Finding more things in Old Village                                                                                                 // # Finding more things in Old Village

        // ## | $CardName       |                                                                                                               // ## | $CardName       |

        // ## |-----------------|                                                                                                               // ## |-----------------|

        // ## | Apple           |                                                                                                               // ## | Apple           |
        context.givenANewGameWithAStackOfNSNSAndNSCards(1, "Old Village", 1, "Old Village Stroll Idea", 1, "Villager");                         // * Given a new game with a stack of 1 "Old Village", 1 "Old Village Stroll Idea" and 1 "Villager" cards.
        context.theSMayCreateASCard("Old Village Stroll Idea", "Apple");                                                                        // * The "Old Village Stroll Idea" may create a "Apple" card.
        context.givenThatTheOddsAreThatWeWillGetASFromTheSCard("Apple", "Old Village");                                                         // * Given that the odds are that we will get a "Apple" from the "Old Village" card.
        context.endTheCurrentMoon();                                                                                                            // * End the current moon.
        context.thereShouldBeNStacksOfNSNSNSAndNSCards(1, 1, "Old Village Stroll Idea", 1, "Old Village", 1, "Villager", 1, "Apple");           // * There should be 1 stacks of 1 "Old Village Stroll Idea", 1 "Old Village", 1 "Villager" and 1 "Apple" cards.
        // # Finding more things in Old Village                                                                                                 // # Finding more things in Old Village

        // ## | $CardName       |                                                                                                               // ## | $CardName       |

        // ## |-----------------|                                                                                                               // ## |-----------------|

        // ## | Villager        |                                                                                                               // ## | Villager        |
        context.givenANewGameWithAStackOfNSNSAndNSCards(1, "Old Village", 1, "Old Village Stroll Idea", 1, "Villager");                         // * Given a new game with a stack of 1 "Old Village", 1 "Old Village Stroll Idea" and 1 "Villager" cards.
        context.theSMayCreateASCard("Old Village Stroll Idea", "Villager");                                                                     // * The "Old Village Stroll Idea" may create a "Villager" card.
        context.givenThatTheOddsAreThatWeWillGetASFromTheSCard("Villager", "Old Village");                                                      // * Given that the odds are that we will get a "Villager" from the "Old Village" card.
        context.endTheCurrentMoon();                                                                                                            // * End the current moon.
        context.thereShouldBeNStacksOfNSNSNSAndNSCards(1, 1, "Old Village Stroll Idea", 1, "Old Village", 1, "Villager", 1, "Villager");        // * There should be 1 stacks of 1 "Old Village Stroll Idea", 1 "Old Village", 1 "Villager" and 1 "Villager" cards.
        // # Finding more things in Old Village                                                                                                 // # Finding more things in Old Village

        // ## | $CardName       |                                                                                                               // ## | $CardName       |

        // ## |-----------------|                                                                                                               // ## |-----------------|

        // ## | Bone            |                                                                                                               // ## | Bone            |
        context.givenANewGameWithAStackOfNSNSAndNSCards(1, "Old Village", 1, "Old Village Stroll Idea", 1, "Villager");                         // * Given a new game with a stack of 1 "Old Village", 1 "Old Village Stroll Idea" and 1 "Villager" cards.
        context.theSMayCreateASCard("Old Village Stroll Idea", "Bone");                                                                         // * The "Old Village Stroll Idea" may create a "Bone" card.
        context.givenThatTheOddsAreThatWeWillGetASFromTheSCard("Bone", "Old Village");                                                          // * Given that the odds are that we will get a "Bone" from the "Old Village" card.
        context.endTheCurrentMoon();                                                                                                            // * End the current moon.
        context.thereShouldBeNStacksOfNSNSNSAndNSCards(1, 1, "Old Village Stroll Idea", 1, "Old Village", 1, "Villager", 1, "Bone");            // * There should be 1 stacks of 1 "Old Village Stroll Idea", 1 "Old Village", 1 "Villager" and 1 "Bone" cards.
        // # Finding more things in Old Village                                                                                                 // # Finding more things in Old Village

        // ## | $CardName       |                                                                                                               // ## | $CardName       |

        // ## |-----------------|                                                                                                               // ## |-----------------|

        // ## | Wolf            |                                                                                                               // ## | Wolf            |
        context.givenANewGameWithAStackOfNSNSAndNSCards(1, "Old Village", 1, "Old Village Stroll Idea", 1, "Villager");                         // * Given a new game with a stack of 1 "Old Village", 1 "Old Village Stroll Idea" and 1 "Villager" cards.
        context.theSMayCreateASCard("Old Village Stroll Idea", "Wolf");                                                                         // * The "Old Village Stroll Idea" may create a "Wolf" card.
        context.givenThatTheOddsAreThatWeWillGetASFromTheSCard("Wolf", "Old Village");                                                          // * Given that the odds are that we will get a "Wolf" from the "Old Village" card.
        context.endTheCurrentMoon();                                                                                                            // * End the current moon.
        context.thereShouldBeNStacksOfNSNSNSAndNSCards(1, 1, "Old Village Stroll Idea", 1, "Old Village", 1, "Villager", 1, "Wolf");            // * There should be 1 stacks of 1 "Old Village Stroll Idea", 1 "Old Village", 1 "Villager" and 1 "Wolf" cards.
        // # Finding more things in Old Village                                                                                                 // # Finding more things in Old Village

        // ## | $CardName       |                                                                                                               // ## | $CardName       |

        // ## |-----------------|                                                                                                               // ## |-----------------|

        // ## | Stone           |                                                                                                               // ## | Stone           |
        context.givenANewGameWithAStackOfNSNSAndNSCards(1, "Old Village", 1, "Old Village Stroll Idea", 1, "Villager");                         // * Given a new game with a stack of 1 "Old Village", 1 "Old Village Stroll Idea" and 1 "Villager" cards.
        context.theSMayCreateASCard("Old Village Stroll Idea", "Stone");                                                                        // * The "Old Village Stroll Idea" may create a "Stone" card.
        context.givenThatTheOddsAreThatWeWillGetASFromTheSCard("Stone", "Old Village");                                                         // * Given that the odds are that we will get a "Stone" from the "Old Village" card.
        context.endTheCurrentMoon();                                                                                                            // * End the current moon.
        context.thereShouldBeNStacksOfNSNSNSAndNSCards(1, 1, "Old Village Stroll Idea", 1, "Old Village", 1, "Villager", 1, "Stone");           // * There should be 1 stacks of 1 "Old Village Stroll Idea", 1 "Old Village", 1 "Villager" and 1 "Stone" cards.
        // # Finding more things in Old Village                                                                                                 // # Finding more things in Old Village

        // ## | $CardName       |                                                                                                               // ## | $CardName       |

        // ## |-----------------|                                                                                                               // ## |-----------------|

        // ## | Gold            |                                                                                                               // ## | Gold            |
        context.givenANewGameWithAStackOfNSNSAndNSCards(1, "Old Village", 1, "Old Village Stroll Idea", 1, "Villager");                         // * Given a new game with a stack of 1 "Old Village", 1 "Old Village Stroll Idea" and 1 "Villager" cards.
        context.theSMayCreateASCard("Old Village Stroll Idea", "Gold");                                                                         // * The "Old Village Stroll Idea" may create a "Gold" card.
        context.givenThatTheOddsAreThatWeWillGetASFromTheSCard("Gold", "Old Village");                                                          // * Given that the odds are that we will get a "Gold" from the "Old Village" card.
        context.endTheCurrentMoon();                                                                                                            // * End the current moon.
        context.thereShouldBeNStacksOfNSNSNSAndNSCards(1, 1, "Old Village Stroll Idea", 1, "Old Village", 1, "Villager", 1, "Gold");            // * There should be 1 stacks of 1 "Old Village Stroll Idea", 1 "Old Village", 1 "Villager" and 1 "Gold" cards.
        // # Finding more things in Old Village                                                                                                 // # Finding more things in Old Village

        // ## | $CardName       |                                                                                                               // ## | $CardName       |

        // ## |-----------------|                                                                                                               // ## |-----------------|

        // ## | Iron            |                                                                                                               // ## | Iron            |
        context.givenANewGameWithAStackOfNSNSAndNSCards(1, "Old Village", 1, "Old Village Stroll Idea", 1, "Villager");                         // * Given a new game with a stack of 1 "Old Village", 1 "Old Village Stroll Idea" and 1 "Villager" cards.
        context.theSMayCreateASCard("Old Village Stroll Idea", "Iron");                                                                         // * The "Old Village Stroll Idea" may create a "Iron" card.
        context.givenThatTheOddsAreThatWeWillGetASFromTheSCard("Iron", "Old Village");                                                          // * Given that the odds are that we will get a "Iron" from the "Old Village" card.
        context.endTheCurrentMoon();                                                                                                            // * End the current moon.
        context.thereShouldBeNStacksOfNSNSNSAndNSCards(1, 1, "Old Village Stroll Idea", 1, "Old Village", 1, "Villager", 1, "Iron");            // * There should be 1 stacks of 1 "Old Village Stroll Idea", 1 "Old Village", 1 "Villager" and 1 "Iron" cards.
        // # Finding more things in Old Village                                                                                                 // # Finding more things in Old Village

        // ## | $CardName       |                                                                                                               // ## | $CardName       |

        // ## |-----------------|                                                                                                               // ## |-----------------|

        // ## | Pear            |                                                                                                               // ## | Pear            |
        context.givenANewGameWithAStackOfNSNSAndNSCards(1, "Old Village", 1, "Old Village Stroll Idea", 1, "Villager");                         // * Given a new game with a stack of 1 "Old Village", 1 "Old Village Stroll Idea" and 1 "Villager" cards.
        context.theSMayCreateASCard("Old Village Stroll Idea", "Pear");                                                                         // * The "Old Village Stroll Idea" may create a "Pear" card.
        context.givenThatTheOddsAreThatWeWillGetASFromTheSCard("Pear", "Old Village");                                                          // * Given that the odds are that we will get a "Pear" from the "Old Village" card.
        context.endTheCurrentMoon();                                                                                                            // * End the current moon.
        context.thereShouldBeNStacksOfNSNSNSAndNSCards(1, 1, "Old Village Stroll Idea", 1, "Old Village", 1, "Villager", 1, "Pear");            // * There should be 1 stacks of 1 "Old Village Stroll Idea", 1 "Old Village", 1 "Villager" and 1 "Pear" cards.
        // # Finding more things in Old Village                                                                                                 // # Finding more things in Old Village

        // ## | $CardName       |                                                                                                               // ## | $CardName       |

        // ## |-----------------|                                                                                                               // ## |-----------------|

        // ## | Diamond         |                                                                                                               // ## | Diamond         |
        context.givenANewGameWithAStackOfNSNSAndNSCards(1, "Old Village", 1, "Old Village Stroll Idea", 1, "Villager");                         // * Given a new game with a stack of 1 "Old Village", 1 "Old Village Stroll Idea" and 1 "Villager" cards.
        context.theSMayCreateASCard("Old Village Stroll Idea", "Diamond");                                                                      // * The "Old Village Stroll Idea" may create a "Diamond" card.
        context.givenThatTheOddsAreThatWeWillGetASFromTheSCard("Diamond", "Old Village");                                                       // * Given that the odds are that we will get a "Diamond" from the "Old Village" card.
        context.endTheCurrentMoon();                                                                                                            // * End the current moon.
        context.thereShouldBeNStacksOfNSNSNSAndNSCards(1, 1, "Old Village Stroll Idea", 1, "Old Village", 1, "Villager", 1, "Diamond");         // * There should be 1 stacks of 1 "Old Village Stroll Idea", 1 "Old Village", 1 "Villager" and 1 "Diamond" cards.
        // # Finding more things in Old Village                                                                                                 // # Finding more things in Old Village

        // ## | $CardName       |                                                                                                               // ## | $CardName       |

        // ## |-----------------|                                                                                                               // ## |-----------------|

        // ## | Pickaxe         |                                                                                                               // ## | Pickaxe         |
        context.givenANewGameWithAStackOfNSNSAndNSCards(1, "Old Village", 1, "Old Village Stroll Idea", 1, "Villager");                         // * Given a new game with a stack of 1 "Old Village", 1 "Old Village Stroll Idea" and 1 "Villager" cards.
        context.theSMayCreateASCard("Old Village Stroll Idea", "Pickaxe");                                                                      // * The "Old Village Stroll Idea" may create a "Pickaxe" card.
        context.givenThatTheOddsAreThatWeWillGetASFromTheSCard("Pickaxe", "Old Village");                                                       // * Given that the odds are that we will get a "Pickaxe" from the "Old Village" card.
        context.endTheCurrentMoon();                                                                                                            // * End the current moon.
        context.thereShouldBeNStacksOfNSNSNSAndNSCards(1, 1, "Old Village Stroll Idea", 1, "Old Village", 1, "Villager", 1, "Pickaxe");         // * There should be 1 stacks of 1 "Old Village Stroll Idea", 1 "Old Village", 1 "Villager" and 1 "Pickaxe" cards.
        // # Finding more things in Old Village                                                                                                 // # Finding more things in Old Village

        // ## | $CardName       |                                                                                                               // ## | $CardName       |

        // ## |-----------------|                                                                                                               // ## |-----------------|

        // ## | Militia         |                                                                                                               // ## | Militia         |
        context.givenANewGameWithAStackOfNSNSAndNSCards(1, "Old Village", 1, "Old Village Stroll Idea", 1, "Villager");                         // * Given a new game with a stack of 1 "Old Village", 1 "Old Village Stroll Idea" and 1 "Villager" cards.
        context.theSMayCreateASCard("Old Village Stroll Idea", "Militia");                                                                      // * The "Old Village Stroll Idea" may create a "Militia" card.
        context.givenThatTheOddsAreThatWeWillGetASFromTheSCard("Militia", "Old Village");                                                       // * Given that the odds are that we will get a "Militia" from the "Old Village" card.
        context.endTheCurrentMoon();                                                                                                            // * End the current moon.
        context.thereShouldBeNStacksOfNSNSNSAndNSCards(1, 1, "Old Village Stroll Idea", 1, "Old Village", 1, "Villager", 1, "Militia");         // * There should be 1 stacks of 1 "Old Village Stroll Idea", 1 "Old Village", 1 "Villager" and 1 "Militia" cards.
        // # Finding more things in Old Village                                                                                                 // # Finding more things in Old Village

        // ## | $CardName       |                                                                                                               // ## | $CardName       |

        // ## |-----------------|                                                                                                               // ## |-----------------|

        // ## | Sword           |                                                                                                               // ## | Sword           |
        context.givenANewGameWithAStackOfNSNSAndNSCards(1, "Old Village", 1, "Old Village Stroll Idea", 1, "Villager");                         // * Given a new game with a stack of 1 "Old Village", 1 "Old Village Stroll Idea" and 1 "Villager" cards.
        context.theSMayCreateASCard("Old Village Stroll Idea", "Sword");                                                                        // * The "Old Village Stroll Idea" may create a "Sword" card.
        context.givenThatTheOddsAreThatWeWillGetASFromTheSCard("Sword", "Old Village");                                                         // * Given that the odds are that we will get a "Sword" from the "Old Village" card.
        context.endTheCurrentMoon();                                                                                                            // * End the current moon.
        context.thereShouldBeNStacksOfNSNSNSAndNSCards(1, 1, "Old Village Stroll Idea", 1, "Old Village", 1, "Villager", 1, "Sword");           // * There should be 1 stacks of 1 "Old Village Stroll Idea", 1 "Old Village", 1 "Villager" and 1 "Sword" cards.
        // # Finding more things in Old Village                                                                                                 // # Finding more things in Old Village

        // ## | $CardName       |                                                                                                               // ## | $CardName       |

        // ## |-----------------|                                                                                                               // ## |-----------------|

        // ## | Cow             |                                                                                                               // ## | Cow             |
        context.givenANewGameWithAStackOfNSNSAndNSCards(1, "Old Village", 1, "Old Village Stroll Idea", 1, "Villager");                         // * Given a new game with a stack of 1 "Old Village", 1 "Old Village Stroll Idea" and 1 "Villager" cards.
        context.theSMayCreateASCard("Old Village Stroll Idea", "Cow");                                                                          // * The "Old Village Stroll Idea" may create a "Cow" card.
        context.givenThatTheOddsAreThatWeWillGetASFromTheSCard("Cow", "Old Village");                                                           // * Given that the odds are that we will get a "Cow" from the "Old Village" card.
        context.endTheCurrentMoon();                                                                                                            // * End the current moon.
        context.thereShouldBeNStacksOfNSNSNSAndNSCards(1, 1, "Old Village Stroll Idea", 1, "Old Village", 1, "Villager", 1, "Cow");             // * There should be 1 stacks of 1 "Old Village Stroll Idea", 1 "Old Village", 1 "Villager" and 1 "Cow" cards.
        // # Finding more things in Old Village                                                                                                 // # Finding more things in Old Village

        // ## | $CardName       |                                                                                                               // ## | $CardName       |

        // ## |-----------------|                                                                                                               // ## |-----------------|

        // ## | Wood            |                                                                                                               // ## | Wood            |
        context.givenANewGameWithAStackOfNSNSAndNSCards(1, "Old Village", 1, "Old Village Stroll Idea", 1, "Villager");                         // * Given a new game with a stack of 1 "Old Village", 1 "Old Village Stroll Idea" and 1 "Villager" cards.
        context.theSMayCreateASCard("Old Village Stroll Idea", "Wood");                                                                         // * The "Old Village Stroll Idea" may create a "Wood" card.
        context.givenThatTheOddsAreThatWeWillGetASFromTheSCard("Wood", "Old Village");                                                          // * Given that the odds are that we will get a "Wood" from the "Old Village" card.
        context.endTheCurrentMoon();                                                                                                            // * End the current moon.
        context.thereShouldBeNStacksOfNSNSNSAndNSCards(1, 1, "Old Village Stroll Idea", 1, "Old Village", 1, "Villager", 1, "Wood");            // * There should be 1 stacks of 1 "Old Village Stroll Idea", 1 "Old Village", 1 "Villager" and 1 "Wood" cards.
        // # Finding more things in Old Village                                                                                                 // # Finding more things in Old Village

        // ## | $CardName       |                                                                                                               // ## | $CardName       |

        // ## |-----------------|                                                                                                               // ## |-----------------|

        // ## | Magic Component |                                                                                                               // ## | Magic Component |
        context.givenANewGameWithAStackOfNSNSAndNSCards(1, "Old Village", 1, "Old Village Stroll Idea", 1, "Villager");                         // * Given a new game with a stack of 1 "Old Village", 1 "Old Village Stroll Idea" and 1 "Villager" cards.
        context.theSMayCreateASCard("Old Village Stroll Idea", "Magic Component");                                                              // * The "Old Village Stroll Idea" may create a "Magic Component" card.
        context.givenThatTheOddsAreThatWeWillGetASFromTheSCard("Magic Component", "Old Village");                                               // * Given that the odds are that we will get a "Magic Component" from the "Old Village" card.
        context.endTheCurrentMoon();                                                                                                            // * End the current moon.
        context.thereShouldBeNStacksOfNSNSNSAndNSCards(1, 1, "Old Village Stroll Idea", 1, "Old Village", 1, "Villager", 1, "Magic Component"); // * There should be 1 stacks of 1 "Old Village Stroll Idea", 1 "Old Village", 1 "Villager" and 1 "Magic Component" cards.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
