package com.drpicox.game.location;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221105_FindingThingsInOldVillage_Test {

    @Autowired Post_20221105_FindingThingsInOldVillage_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-11-05_finding_things_in_old_village", "cbd46221101e1a47d7f48d11f866ef70");
        context.beforeTest();

        // # Finding things in Old Village                                                                                            // # Finding things in Old Village

        // ## | $CardName       |                                                                                                     // ## | $CardName       |

        // ## |-----------------|                                                                                                     // ## |-----------------|

        // ## | Berry           |                                                                                                     // ## | Berry           |
        context.givenANewGameWithAStackOfNSNSAndNSCards(1, "Old Village Stroll Idea", 1, "Old Village", 1, "Villager");               // * Given a new game with a stack of 1 "Old Village Stroll Idea", 1 "Old Village" and 1 "Villager" cards.
        context.theSMayCreateASCard("Old Village Stroll Idea", "Berry");                                                              // * The "Old Village Stroll Idea" may create a "Berry" card.
        context.givenThatTheOddsAreThatWeWillGetASFromTheSCard("Berry", "Old Village");                                               // * Given that the odds are that we will get a "Berry" from the "Old Village" card.
        context.endTheCurrentMoon();                                                                                                  // * End the current moon.
        context.thereShouldBeNStacksOfNSNSNSAndNSCards(1, 1, "Old Village Stroll Idea", 1, "Old Village", 1, "Villager", 1, "Berry"); // * There should be 1 stacks of 1 "Old Village Stroll Idea", 1 "Old Village", 1 "Villager" and 1 "Berry" cards.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
