package com.drpicox.game.game;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20220717_BushesVillagersAndBerries_Test {

    @Autowired Post_20220717_BushesVillagersAndBerries_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-07-17_bushes_villagers_and_berries", "187c6ace9199129be617f29fe9a5cfe4");
        context.beforeTest();

        // # Bushes, Villagers and Berries             // # Bushes, Villagers and Berries

        // ## The game                                 // ## The game
        context.enterTheGame();                        // * Enter the game.
        context.thereShouldBeNSCards(1, "Villager");   // * There should be 1 "Villager" cards.
        context.thereShouldBeNSCards(1, "Berry Bush"); // * There should be 1 "Berry Bush" cards.
        context.thereShouldBeNSCards(1, "Berry");      // * There should be 1 "Berry" cards.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
