package com.drpicox.game.game;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221010_CoinsAndPoints_Test {

    @Autowired Post_20221010_CoinsAndPoints_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-10-10_coins_and_points", "fe84ed01187ec62528843c467dcb53db");
        context.beforeTest();

        // # coins and points                      // # coins and points

        // ## The game                             // ## The game
        context.enterTheGame();                    // * Enter the game.
        context.thereShouldBeNSCards(7, "Coins");  // * There should be 7 "Coins" cards.
        context.thereShouldBeNSCards(0, "Points"); // * There should be 0 "Points" cards.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
