package com.drpicox.game.weapon;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221127_Rod_Test {

    @Autowired Post_20221127_Rod_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-11-27_rod", "79f1a50994a2dd7db8d4adbcee3e59a6");
        context.beforeTest();

        // # Rod                                                                                                  // # Rod

        // ## How to create the rod                                                                               // ## How to create the rod
        context.givenANewGameWithAStackOfNSNSNSAndNSCards(1, "Build Idea", 1, "Wizard", 3, "Wood", 1, "Diamond"); // * Given a new game with a stack of 1 "Build Idea", 1 "Wizard", 3 "Wood" and 1 "Diamond" cards.
        context.endTheCurrentMoon();                                                                              // * End the current moon.
        context.thereShouldBeNStacksOfNSNSNSCards(1, 1, "Build Idea", 1, "Wizard", 1, "Rod");                     // * There should be 1 stacks of 1 "Build Idea", 1 "Wizard", 1 "Rod" cards.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
