package com.drpicox.game.weapon;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221027_Sword_Test {

    @Autowired Post_20221027_Sword_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-10-27_sword", "0d98beb4a9d1d0e2c862793ccb765a1d");
        context.beforeTest();

        // # Sword                                                                                               // # Sword

        // ## How to create the sword                                                                            // ## How to create the sword
        context.givenANewGameWithAStackOfNSNSNSAndNSCards(1, "Build Idea", 1, "Villager", 1, "Wood", 2, "Iron"); // * Given a new game with a stack of 1 "Build Idea", 1 "Villager", 1 "Wood" and 2 "Iron" cards.
        context.endTheCurrentMoon();                                                                             // * End the current moon.
        context.thereShouldBeNStacksOfNSNSNSCards(1, 1, "Build Idea", 1, "Villager", 1, "Sword");                // * There should be 1 stacks of 1 "Build Idea", 1 "Villager", 1 "Sword" cards

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
