package com.drpicox.game.weapon;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221205_Shotgun_Test {

    @Autowired Post_20221205_Shotgun_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-12-05_shotgun", "d63130ce475cced60d982867358772f0");
        context.beforeTest();

        // # Shotgun                                                                                             // # Shotgun

        // ## How to create a shotgun                                                                            // ## How to create a shotgun
        context.givenANewGameWithAStackOfNSNSNSAndNSCards(1, "Build Idea", 1, "Villager", 3, "Wood", 2, "Iron"); // * Given a new game with a stack of 1 "Build Idea", 1 "Villager", 3 "Wood" and 2 "Iron" cards.
        context.endTheCurrentMoon();                                                                             // * End the current moon.
        context.thereShouldBeNStacksOfNSNSNSCards(1, 1, "Build Idea", 1, "Villager", 1, "Shotgun");              // * There should be 1 stacks of 1 "Build Idea", 1 "Villager", 1 "Shotgun" cards

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
