package com.drpicox.game.weapon;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221110_Bow_Test {

    @Autowired Post_20221110_Bow_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-11-10_bow", "d4c023cbd15b73955785de223109c7f2");
        context.beforeTest();

        // # Bow                                                                                                   // # Bow

        // ## How to create a bow                                                                                  // ## How to create a bow
        context.givenANewGameWithAStackOfNSNSNSAndNSCards(1, "Build Idea", 1, "Villager", 3, "Wood", 2, "String"); // * Given a new game with a stack of 1 "Build Idea", 1 "Villager", 3 "Wood" and 2 "String" cards.
        context.endTheCurrentMoon();                                                                               // * End the current moon.
        context.thereShouldBeNStacksOfNSNSNSCards(1, 1, "Build Idea", 1, "Villager", 1, "Bow");                    // * There should be 1 stacks of 1 "Build Idea", 1 "Villager", 1 "Bow" cards.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
