package com.drpicox.game.material;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221124_BoneFragment_Test {

    @Autowired Post_20221124_BoneFragment_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-11-24_bone_fragment", "a1867e8445446fbe948cc9b31cc21476");
        context.beforeTest();

        // # Bone Fragment                                                                                   // # Bone Fragment
        // # What is the Bone Fragment for?                                                                  // # What is the Bone Fragment for?
        context.givenANewGameWithAStackOfNSNSAndNSCards(1, "Build Idea", 1, "Villager", 3, "Bone Fragment"); // * Given a new game with a stack of 1 "Build Idea", 1 "Villager" and 3 "Bone Fragment" cards.
        context.endTheCurrentMoon();                                                                         // * End the current moon.
        context.thereShouldBeNStacksOfNSNSAndNSCards(1, 1, "Build Idea", 1, "Villager", 1, "Bone");          // * There should be 1 stacks of 1 "Build Idea", 1 "Villager" and 1 "Bone" cards.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
