package com.drpicox.game.material;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221124_Branch_Test {

    @Autowired Post_20221124_Branch_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-11-24_branch", "c986bffbdb71e9562cbf1ebb6c270dce");
        context.beforeTest();

        // # Branch                                                                                   // # Branch
        // # What is the branch for?                                                                  // # What is the branch for?
        context.givenANewGameWithAStackOfNSNSAndNSCards(1, "Build Idea", 1, "Villager", 2, "Branch"); // * Given a new game with a stack of 1 "Build Idea", 1 "Villager"and 2 "Branch" cards.
        context.endTheCurrentMoon();                                                                  // * End the current moon.
        context.thereShouldBeNStacksOfNSNSAndNSCards(1, 1, "Build Idea", 1, "Villager", 1, "Wood");   // * There should be 1 stacks of 1 "Build Idea", 1 "Villager" and 1 "Wood" cards.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
